# Generated by Django 3.2.9 on 2021-11-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='matricula',
            field=models.FloatField(default=0),
        ),
    ]
