# Generated by Django 3.2.9 on 2021-11-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.FloatField()),
            ],
        ),
    ]
