# Generated by Django 3.2.9 on 2021-11-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_supervisor_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='rfc',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidoMaterno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidoPaterno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='matricula',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
