# Generated by Django 3.2.9 on 2021-11-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('NumerodeSucursal', models.FloatField()),
                ('direccion', models.TextField()),
                ('codigopostal', models.FloatField()),
            ],
        ),
    ]
